[package]
name = "stdio-utils"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/jprendes/stdio-utils"
homepage = "https://github.com/jprendes/stdio-utils"

[dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3"
